
unitNames = {
    "ual0001": "Armored Command Unit",
    "url0001": "Armored Command Unit",
    "uel0001": "Armored Command Unit",
    "xsl0001": "Armored Command Unit",
    "ual0301": "T3 Support Armored Command Unit",
    "url0301": "T3 Support Armored Command Unit",
    "uel0301": "T3 Support Armored Command Unit",
    "xsl0301": "T3 Support Armored Command Unit",
    "ual0105": "T1 Engineer",
    "url0105": "T1 Engineer",
    "uel0105": "T1 Engineer",
    "xsl0105": "T1 Engineer: Iya-istle",
    "ual0208": "T2 Engineer",
    "url0208": "T2 Engineer",
    "xrb0104": "T2 Engineering Station: The Hive",
    "xrb0204": "T2 Engineering Station: The Hive",
    "xrb0304": "T2 Engineering Station: The Hive",
    "uel0208": "T2 Engineer",
    "xel0209": "T2 Field Engineer: Sparky",
    "xsl0208": "T2 Engineer: Iya",
    "ual0309": "T3 Engineer",
    "url0309": "T3 Engineer",
    "uel0309": "T3 Engineer",
    "xsl0309": "T3 Engineer: Iyathuum",
    "xsl0402": "EX Unidentified Residual Energy Signature: Othuy",
    "uab0102": "T1 Air Factory",
    "uab0101": "T1 Land Factory",
    "uab0103": "T1 Naval Factory",
    "urb0102": "T1 Air Factory",
    "urb0101": "T1 Land Factory",
    "urb0103": "T1 Naval Factory",
    "ueb0102": "T1 Air Factory",
    "ueb0101": "T1 Land Factory",
    "ueb0103": "T1 Naval Factory",
    "xsb0102": "T1 Air Factory: Ia-iya",
    "xsb0101": "T1 Land Factory: Hethiya",
    "xsb0103": "T1 Naval Factory: Uosiya",
    "uab0202": "T2 Air Factory",
    "uab0201": "T2 Land Factory",
    "uab0203": "T2 Naval Factory",
    "urb0202": "T2 Air Factory",
    "xrl0004": "T2 Crab Egg (Flak)",
    "urb0201": "T2 Land Factory",
    "urb0203": "T2 Naval Factory",
    "ueb0202": "T2 Air Factory",
    "ueb0201": "T2 Land Factory",
    "ueb0203": "T2 Naval Factory",
    "xsb0202": "T2 Air Factory: Ia-iya",
    "xsb0201": "T2 Land Factory: Hethiya",
    "xsb0203": "T2 Naval Factory: Uosiya",
    "uab0302": "T3 Air Factory",
    "uab0301": "T3 Land Factory",
    "uab0303": "T3 Naval Factory",
    "uab0304": "T3 Quantum Gateway: Portal",
    "urb0302": "T3 Air Factory",
    "xrl0005": "T3 Crab Egg (Artillery)",
    "xrl0003": "T3 Crab Egg (Brick)",
    "xrl0002": "T3 Crab Egg (Engineer)",
    "urb0301": "T3 Land Factory",
    "urb0303": "T3 Naval Factory",
    "urb0304": "T3 Quantum Gateway: Summoner",
    "ueb0302": "T3 Air Factory",
    "ueb0301": "T3 Land Factory",
    "ueb0303": "T3 Naval Factory",
    "ueb0304": "T3 Quantum Gateway: QGW R-32",
    "xsb0302": "T3 Air Factory: Ia-iya",
    "xsb0301": "T3 Land Factory: Hethiya",
    "xsb0303": "T3 Naval Factory: Uosiya",
    "xsb0304": "T3 Quantum Gateway: Aezthu-uhthe",
    "uab1105": "T1 Energy Storage",
    "uab1102": "T1 Hydrocarbon Power Plant",
    "uab1103": "T1 Mass Extractor",
    "uab1106": "T1 Mass Storage",
    "uab1101": "T1 Power Generator",
    "urb1105": "T1 Energy Storage",
    "urb1102": "T1 Hydrocarbon Power Plant",
    "urb1103": "T1 Mass Extractor",
    "urb1106": "T1 Mass Storage",
    "urb1101": "T1 Power Generator",
    "ueb1105": "T1 Energy Storage",
    "ueb1102": "T1 Hydrocarbon Power Plant: HCPP - X1000",
    "ueb1103": "T1 Mass Extractor: Mass Pump 1",
    "ueb1106": "T1 Mass Storage",
    "ueb1101": "T1 Power Generator",
    "xsb1105": "T1 Energy Storage: Vishuyal",
    "xsb1102": "T1 Hydrocarbon Power Plant: Uya-atoh",
    "xsb1103": "T1 Mass Extractor: Hyalatoh",
    "xsb1106": "T1 Mass Storage: Vishyal",
    "xsb1101": "T1 Power Generator: Uya-iya",
    "uab1202": "T2 Mass Extractor",
    "uab1104": "T2 Mass Fabricator",
    "uab1201": "T2 Power Generator",
    "urb1202": "T2 Mass Extractor",
    "urb1104": "T2 Mass Fabricator",
    "urb1201": "T2 Power Generator",
    "ueb1202": "T2 Mass Extractor: Mass Pump 2",
    "ueb1104": "T2 Mass Fabricator",
    "ueb1201": "T2 Power Generator: EG - 200 Fusion Reactor",
    "xsb1202": "T2 Mass Extractor: Hyalatoh",
    "xsb1104": "T2 Mass Fabricator: Hyaliya",
    "xsb1201": "T2 Power Generator: Uya-iya",
    "uab1302": "T3 Mass Extractor",
    "uab1303": "T3 Mass Fabricator",
    "uab1301": "T3 Power Generator: Quantum Reactor",
    "urb1302": "T3 Mass Extractor",
    "urb1303": "T3 Mass Fabricator",
    "urb1301": "T3 Power Generator: Ion Reactor",
    "ueb1302": "T3 Mass Extractor: Mass Pump 3",
    "ueb1303": "T3 Mass Fabricator",
    "ueb1301": "T3 Power Generator: EG 900 Fusion Reactor",
    "xsb1302": "T3 Mass Extractor: Hyalatoh",
    "xsb1303": "T3 Mass Fabricator: Hyaliya",
    "xsb1301": "T3 Power Generator: Uya-iya",
    "xab1401": "EX Experimental Resource Generator: Paragon",
    "uab2104": "T1 Anti-Air Turret: Seeker",
    "uab2101": "T1 Point Defense: Erupter",
    "uab2109": "T1 Torpedo Launcher: Tide",
    "urb2104": "T1 Anti-Air Turret: Tracer",
    "urb2101": "T1 Point Defense: Auto Gun",
    "urb2109": "T1 Torpedo Launcher: Scuttle",
    "ueb2104": "T1 Anti-Air Turret: DA1 Railgun",
    "ueb2101": "T1 Point Defense: DM1 Plasma Cannon",
    "ueb2109": "T1 Torpedo Launcher: DN1",
    "xsb2104": "T1 Anti-Air Defense: Ialla",
    "xsb2101": "T1 Point Defense: Uttaus",
    "xsb2109": "T1 Torpedo Launcher: Sou-atha",
    "uab2204": "T2 Anti-Air Flak Artillery: Marr",
    "uab2303": "T2 Artillery Installation: Miasma",
    "uab2301": "T2 Point Defense: Oblivion",
    "uab2108": "T2 Tactical Missile Launcher: Serpentine",
    "uab2205": "T2 Torpedo Launcher: Wave Break",
    "urb2204": "T2 Anti-Air Flak Artillery: Burst Master",
    "urb2303": "T2 Artillery Installation: Gunther",
    "urb2301": "T2 Point Defense: Cerberus",
    "urb2108": "T2 Tactical Missile Launcher: TML-4",
    "urb2205": "T2 Torpedo Launcher: Nanite Torpedo Array",
    "ueb2204": "T2 Anti-Air Flak Artillery: Air Cleaner",
    "ueb2303": "T2 Artillery Installation: Klink Hammer",
    "ueb2301": "T2 Point Defense: Triad",
    "ueb2108": "T2 Tactical Missile Launcher: Aloha",
    "ueb2205": "T2 Torpedo Launcher: Tsunami",
    "xsb2204": "T2 Anti-Air Flak Artillery: Sinnatha",
    "xsb2303": "T2 Artillery Installation: Zthuthaam",
    "xsb2301": "T2 Point Defense: Uttaushala",
    "xsb2108": "T2 Tactical Missile Launcher: Ythis",
    "xsb2205": "T2 Torpedo Launcher: Uosthu",
    "uab2304": "T3 Anti-Air SAM Launcher: Transcender",
    "uab2302": "T3 Heavy Artillery Installation: Emissary",
    "xab2307": "T3 Rapid-Fire Artillery Installation: Salvation",
    "uab2305": "T3 Strategic Missile Launcher: Apocalypse",
    "urb2304": "T3 Anti-Air SAM Launcher: Myrmidon",
    "urb2302": "T3 Heavy Artillery Installation: Disruptor",
    "urb2305": "T3 Strategic Missile Launcher: Liberator",
    "xrb2308": "T3 Torpedo Ambushing System: HARMS",
    "ueb2304": "T3 Anti-Air SAM Launcher: Flayer",
    "ueb2302": "T3 Heavy Artillery Installation: Duke",
    "xeb2306": "T3 Heavy Point Defense: Ravager",
    "ueb2305": "T3 Strategic Missile Launcher: Stonager",
    "xsb2304": "T3 Anti-Air Defense: Iathu-ioz",
    "xsb2302": "T3 Heavy Artillery Installation: Hovatham",
    "xsb2305": "T3 Strategic Missile Launcher: Hastue",
    "ueb2401": "EX Experimental Artillery: Mavor",
    "xsb2401": "EX Experimental Missile Launcher: Yolona Oss",
    "uab4202": "T2 Shield Generator: Shield of Light",
    "uab4203": "T2 Stealth Field Generator: Veil",
    "uab4201": "T2 Tactical Missile Defense: Volcano",
    "urb4202": "T2 Shield Generator: ED1",
    "urb4204": "T2 Shield Generator: ED2",
    "urb4205": "T2 Shield Generator: ED3",
    "urb4206": "T2 Shield Generator: ED4",
    "urb4207": "T2 Shield Generator: ED5",
    "urb4203": "T2 Stealth Field Generator: Twilight",
    "urb4201": "T2 Tactical Missile Defense: Zapper",
    "ueb4202": "T2 Shield Generator: SD - Pulse",
    "ueb4203": "T2 Stealth Field Generator: Scattershield",
    "ueb4201": "T2 Tactical Missile Defense: Buzzkill",
    "xsb4202": "T2 Shield Generator: Atha",
    "xsb4203": "T2 Stealth Field Generator: Sele-ioz",
    "xsb4201": "T2 Tactical Missile Defense: Ythisatha",
    "uab4301": "T3 Heavy Shield Generator: Radiance",
    "uab4302": "T3 Strategic Missile Defense: Patron",
    "xrb3301": "T3 Perimeter Monitoring System: Soothsayer",
    "urb4302": "T3 Strategic Missile Defense: Guardian",
    "ueb4301": "T3 Heavy Shield Generator: HSD Pulse",
    "ueb4302": "T3 Strategic Missile Defense: Nuke Eliminator",
    "xsb4301": "T3 Heavy Shield Generator: Athanuhthe",
    "xsb4302": "T3 Strategic Missile Defense: Ythisioz",
    "uab3101": "T1 Radar System",
    "uab3102": "T1 Sonar System",
    "urb3101": "T1 Radar System: Magno",
    "urb3102": "T1 Sonar System: Noah",
    "ueb3101": "T1 Radar System: SA1 - 1000",
    "ueb3102": "T1 Sonar System: SP1 - 1000",
    "xsb3101": "T1 Radar System: Esel",
    "xsb3102": "T1 Sonar System: Shou",
    "uab3201": "T2 Radar System",
    "uab3202": "T2 Sonar System",
    "urb3201": "T2 Radar System: Magno XR",
    "urb3202": "T2 Sonar System: Flood",
    "xeb0104": "T2 Engineering Station: The Kennel",
    "ueb3201": "T2 Radar System: SA2 - 2000",
    "ueb3202": "T2 Sonar System: SP2 - 2000",
    "xsb3201": "T2 Radar System: Sele-esel",
    "xsb3202": "T2 Sonar System: Shou-esel",
    "uab3104": "T3 Omni Sensor Array: Oculus",
    "xab3301": "T3 Quantum Optics Facility: Eye of Rhianne",
    "uas0305": "T3 Sonar Platform",
    "urb3104": "T3 Omni Sensor Array: Olympus",
    "urs0305": "T3 Sonar Platform: Flood XR",
    "xeb0204": "T3 Engineering Station: The Kennel",
    "ueb3104": "T3 Omni Sensor Array: SA3 - Omni",
    "ues0305": "T3 Sonar Platform: SP3 - 3000",
    "xsb3104": "T3 Omni Sensor Suite: Aezesel",
    "uaa0101": "T1 Air Scout: Mirage",
    "uaa0103": "T1 Attack Bomber: Shimmer",
    "uaa0102": "T1 Interceptor: Conservator",
    "uaa0107": "T1 Light Air Transport: Chariot",
    "ura0101": "T1 Air Scout: Flying Eyes",
    "ura0103": "T1 Attack Bomber: Zeus",
    "ura0102": "T1 Interceptor: Prowler",
    "ura0107": "T1 Light Air Transport: Skyhook",
    "xra0105": "T1 Light Gunship: Jester",
    "uea0101": "T1 Air Scout: Hummingbird",
    "uea0103": "T1 Attack Bomber: Scorcher",
    "uea0001": "T1 Engineering Drone: C-D1 \"Rover\"",
    "uea0003": "T1 Engineering Drone: C-D2 \"Rover\"",
    "xea3204": "T1 Engineering Drone: C-D2 \"Rover-2\"",
    "uea0102": "T1 Interceptor: Cyclone",
    "uea0107": "T1 Light Air Transport: C-6 Courier",
    "xsa0101": "T1 Air Scout: Sele-istle",
    "xsa0103": "T1 Attack Bomber: Sinnve",
    "xsa0102": "T1 Interceptor: Ia-atha",
    "xsa0107": "T1 Light Air Transport: Vish",
    "uaa0104": "T2 Air Transport: Aluminar",
    "xaa0202": "T2 Combat Fighter: Swift Wind",
    "daa0206": "T2 Guided Missile: Mercy",
    "uaa0203": "T2 Gunship: Specter",
    "uaa0204": "T2 Torpedo Bomber: Skimmer",
    "ura0104": "T2 Air Transport: Dragon Fly",
    "dra0202": "T2 Fighter/Bomber: Corsair",
    "ura0203": "T2 Gunship: Renegade",
    "ura0204": "T2 Torpedo Bomber: Cormorant",
    "uea0104": "T2 Air Transport: C14 Star Lifter",
    "dea0202": "T2 Fighter/Bomber: Janus",
    "uea0203": "T2 Gunship: Stinger",
    "uea0204": "T2 Torpedo Bomber: Stork",
    "xsa0104": "T2 Air Transport: Vishala",
    "xsa0202": "T2 Fighter/Bomber: Notha",
    "xsa0203": "T2 Gunship: Vulthoo",
    "xsa0204": "T2 Torpedo Bomber: Uosioz",
    "xaa0305": "T3 AA Gunship: Restorer",
    "uaa0303": "T3 Air-Superiority Fighter: Corona",
    "uaa0302": "T3 Spy Plane: Seer",
    "uaa0304": "T3 Strategic Bomber: Shocker",
    "xaa0306": "T3 Torpedo Bomber: Solace",
    "ura0303": "T3 Air Superiority Fighter: Gemini",
    "xra0305": "T3 Heavy Gunship: Wailer",
    "ura0302": "T3 Spy Plane: Spook",
    "ura0304": "T3 Strategic Bomber: Revenant",
    "uea0303": "T3 Air-Superiority Fighter: Wasp",
    "xea0306": "T3 Heavy Air Transport: Continental",
    "uea0305": "T3 Heavy Gunship: Broadsword",
    "uea0302": "T3 Spy Plane: SR90 Blackbird",
    "uea0304": "T3 Strategic Bomber: Ambassador",
    "xsa0303": "T3 Air-Superiority Fighter: Iazyne",
    "xsa0302": "T3 Spy Plane: Iaselen",
    "xsa0304": "T3 Strategic Bomber: Sinntha",
    "uaa0310": "EX Experimental Aircraft Carrier: CZAR",
    "ura0401": "EX Experimental Gunship: Soul Ripper",
    "xea0002": "EX Defense Satellite",
    "xsa0402": "EX Experimental Bomber: Ahwassa",
    "ual0101": "T1 Land Scout: Spirit",
    "ual0106": "T1 Light Assault Bot: Flare",
    "ual0201": "T1 Light Tank: Aurora",
    "ual0104": "T1 Mobile Anti-Air Gun: Thistle",
    "ual0103": "T1 Mobile Light Artillery: Fervor",
    "url0107": "T1 Assault Bot: Mantis",
    "url0101": "T1 Land Scout: Mole",
    "url0106": "T1 Light Assault Bot: Hunter",
    "url0104": "T1 Mobile Anti-Air Gun: Sky Slammer",
    "url0103": "T1 Mobile Light Artillery: Medusa",
    "uel0101": "T1 Land Scout: Snoop",
    "uel0106": "T1 Light Assault Bot: Mech Marine",
    "uel0201": "T1 Medium Tank: MA12 Striker",
    "uel0104": "T1 Mobile Anti-Air Gun: Archer",
    "uel0103": "T1 Mobile Light Artillery: Lobo",
    "xsl0101": "T1 Combat Scout: Selen",
    "xsl0201": "T1 Medium Tank: Thaam",
    "xsl0104": "T1 Mobile Anti-Air Gun: Ia-istle",
    "xsl0103": "T1 Mobile Light Artillery: Zthuee",
    "xal0203": "T2 Assault Tank: Blaze",
    "ual0202": "T2 Heavy Tank: Obsidian",
    "ual0205": "T2 Mobile AA Flak Artillery: Ascendant",
    "ual0111": "T2 Mobile Missile Launcher: Evensong",
    "ual0307": "T2 Mobile Shield Generator: Asylum",
    "url0203": "T2 Amphibious Tank: Wagner",
    "url0202": "T2 Heavy Tank: Rhino",
    "url0205": "T2 Mobile AA Flak Artillery: Banger",
    "xrl0302": "T2 Mobile Bomb: Fire Beetle",
    "url0111": "T2 Mobile Missile Launcher: Viper",
    "url0306": "T2 Mobile Stealth Field System: Deceiver",
    "drl0204": "T2 Rocket Bot: Hoplite",
    "uel0203": "T2 Amphibious Tank: Riptide",
    "del0204": "T2 Gatling Bot: Mongoose",
    "uel0202": "T2 Heavy Tank: Pillar",
    "uel0205": "T2 Mobile AA Flak Artillery: Sky Boxer",
    "uel0111": "T2 Mobile Missile Launcher: Flapjack",
    "uel0307": "T2 Mobile Shield Generator: Parashield",
    "xsl0202": "T2 Assault Bot: Ilshavoh",
    "xsl0203": "T2 Hover Tank: Yenzyne",
    "xsl0205": "T2 Mobile Anti-Air Cannon: Iashavoh",
    "xsl0111": "T2 Mobile Missile Launcher: Ythisah",
    "ual0303": "T3 Heavy Assault Bot: Harbinger Mark IV",
    "ual0304": "T3 Mobile Heavy Artillery: Serenity",
    "dal0310": "T3 Shield Disruptor: Absolver",
    "xal0305": "T3 Sniper Bot: Sprite Striker",
    "xrl0305": "T3 Armored Assault Bot: The Brick",
    "url0304": "T3 Mobile Heavy Artillery: Trebuchet",
    "url0303": "T3 Siege Assault Bot: Loyalist",
    "xel0305": "T3 Armored Assault Bot: Percival",
    "uel0303": "T3 Heavy Assault Bot: Titan",
    "uel0304": "T3 Mobile Heavy Artillery: Demolisher",
    "xel0306": "T3 Mobile Missile Platform: Spearhead",
    "xsl0304": "T3 Mobile Heavy Artillery: Suthanus",
    "xsl0307": "T3 Mobile Shield Generator: Athanah",
    "xsl0303": "T3 Siege Tank: Othuum",
    "xsl0305": "T3 Sniper Bot: Usha-Ah",
    "ual0401": "EX Experimental Assault Bot: Galactic Colossus",
    "xrl0403": "EX Experimental Megabot: Megalith",
    "url0401": "EX Experimental Mobile Rapid-Fire Artillery: Scathis",
    "url0402": "EX Experimental Spiderbot: Monkeylord",
    "uel0401": "EX Experimental Mobile Factory: Fatboy",
    "xsl0401": "EX Experimental Assault Bot: Ythotha",
    "uas0102": "T1 Attack Boat: Shard",
    "uas0203": "T1 Attack Submarine: Sylph",
    "uas0103": "T1 Frigate: Beacon Class",
    "urs0203": "T1 Attack Submarine: Sliver",
    "urs0103": "T1 Frigate: Trident Class",
    "ues0203": "T1 Attack Submarine: Tigershark",
    "ues0103": "T1 Frigate: Thunderhead Class",
    "xss0203": "T1 Attack Submarine: Sou-istle",
    "xss0103": "T1 Frigate: Hau-esel",
    "uas0202": "T2 Cruiser: Infinity Class",
    "uas0201": "T2 Destroyer: Exodus Class",
    "xas0204": "T2 Submarine Hunter: Vesper",
    "xrs0205": "T2 Counter-Intelligence Boat: CI:18 Mermaid",
    "urs0202": "T2 Cruiser: Siren Class",
    "urs0201": "T2 Destroyer: Salem Class",
    "xrs0204": "T2 Submarine Killer: Barracuda",
    "ues0202": "T2 Cruiser: Governor Class",
    "ues0201": "T2 Destroyer: Valiant Class",
    "xes0205": "T2 Shield Boat: Bulwark",
    "xes0102": "T2 Torpedo Boat: Cooper",
    "xss0202": "T2 Cruiser: Ithalua",
    "xss0201": "T2 Destroyer: Uashavoh",
    "uas0303": "T3 Aircraft Carrier: Keefer Class",
    "uas0302": "T3 Battleship: Omen Class",
    "xas0306": "T3 Missile Ship: Torrent Class",
    "uas0304": "T3 Strategic Missile Submarine: Silencer",
    "urs0303": "T3 Aircraft Carrier: Command Class",
    "urs0302": "T3 Battleship: Galaxy Class",
    "urs0304": "T3 Strategic Missile Submarine: Plan B",
    "xes0307": "T3 Battlecruiser: Neptune Class",
    "ues0302": "T3 Battleship: Summit Class",
    "ues0304": "T3 Strategic Missile Submarine: Ace",
    "xss0303": "T3 Aircraft Carrier: Iavish",
    "xss0302": "T3 Battleship: Hauthuum",
    "xss0304": "T3 Submarine Hunter: Yathsou",
    "uas0401": "EX Experimental Battleship: Tempest",
    "ues0401": "EX Experimental Aircraft Carrier: Atlantis",
    "uab5101": "T1 Wall Section",
    "urb5101": "T1 Wall Section",
    "ueb5101": "T1 Wall Section: Calcicrete",
    "xsb5101": "T1 Wall Section: Haas",
    "uab5202": "T2 Air Staging Facility: Cradle",
    "urb5202": "T2 Air Staging Facility",
    "ueb5202": "T2 Air Staging Facility: Refuel & Repair",
    "xsb5202": "T2 Air Staging Beacon: Iathu-uhthe",
    "xeb2402": "EX Experimental Satellite System: Novax Center"
}


class LuaType:
    (
        NUMBER,
        STRING,
        NIL,
        BOOL,
        LUA,
        LUA_END,
    ) = range(6)


class STITarget:
    (
        NONE,
        Entity,
        Position
    ) = range(3)


class ECmdStreamOp:
    (
        CMDST_Advance,
        # uint32 - number of beats to advance.

        CMDST_SetCommandSource,
        # uint8 - command source

        CMDST_CommandSourceTerminated,
        # no args.

        CMDST_VerifyChecksum,
        # MD5Digest - checksum
        # uint32 - beat number

        CMDST_RequestPause,
        CMDST_Resume,
        CMDST_SingleStep,
        # All with no additional data.

        CMDST_CreateUnit,
        # uint8 - army index
        # string - blueprint ID
        # float - x
        # float - z
        # float - heading

        CMDST_CreateProp,
        # string - blueprint ID
        # Vector3f - location

        CMDST_DestroyEntity,
        # EntId - entity

        CMDST_WarpEntity,
        # EntId - entity
        # VTransform - new transform

        CMDST_ProcessInfoPair,
        # EntId - entity
        # string - arg1
        # string - arg2

        CMDST_IssueCommand,
        # uint32 - num units
        # EntIdSet - units
        # CmdData - command data
        # uint8 - clear queue flag

        CMDST_IssueFactoryCommand,
        # uint32 - num factories
        # EntIdSet - factories
        # CmdData - command data
        # uint8 - clear queue flag

        CMDST_IncreaseCommandCount,
        # CmdId - command id
        # int32 - count delta

        CMDST_DecreaseCommandCount,
        # CmdId - command id
        # int32 - count delta

        CMDST_SetCommandTarget,
        # CmdId - command id
        # STITarget - target

        CMDST_SetCommandType,
        # CmdId - command id
        # EUnitCommandType - type

        CMDST_SetCommandCells,
        # CmdId - command id
        # ListOfCells - list of cells
        # Vector3f - pos

        CMDST_RemoveCommandFromQueue,
        # CmdId - command id
        # EntId - unit

        CMDST_DebugCommand,
        # string -- the debug command string
        # Vector3f -- mouse pos (in world coords)
        # uint8 -- focus army index
        # EntIdSet -- selection

        CMDST_ExecuteLuaInSim,
        # string -- the lua string to evaluate in the sim state

        CMDST_LuaSimCallback,
        # string - callback function name
        # LuaObject - table of function arguments

        CMDST_EndGame,
        # no args.
    ) = range(24)


class EUnitCommandType:
    (
        NONE,
        Stop,
        Move,
        Dive,
        FormMove,
        BuildSiloTactical,
        BuildSiloNuke,
        BuildFactory,
        BuildMobile,
        BuildAssist,
        Attack,
        FormAttack,
        Nuke,
        Tactical,
        Teleport,
        Guard,
        Patrol,
        Ferry,
        FormPatrol,
        Reclaim,
        Repair,
        Capture,
        TransportLoadUnits,
        TransportReverseLoadUnits,
        TransportUnloadUnits,
        TransportUnloadSpecificUnits,
        DetachFromTransport,
        Upgrade,
        Script,
        AssistCommander,
        KillSelf,
        DestroySelf,
        Sacrifice,
        Pause,
        OverCharge,
        AggressiveMove,
        FormAggressiveMove,
        AssistMove,
        SpecialAction,
        Dock,
    ) = range(40)

